<template>
  <BasePage>
    <div class="p-8 sm:p-12 sm:my-12 lg:p-20 lg:my-6 text-text-main">
      <h2 class="text-title text-3xl sm:text-5xl font-bold mb-8 self-center">
        Privacy Policy
      </h2>
      <span class="my-12">
        <span class="important">Effective Date: May 26, 2026</span><br>
        This Privacy Policy explains how FT_CAT handles user information for this school project.
      </span>
      <ul>
        <li class="caseli">
          <h3>1. Information We Collect</h3>
          <p>
            Because you must create a profile to use the site, we collect:<br>
            <ul>
              <li class="pl-4 flex items-center gap-2.5">
                <span class="size-1.5 rounded-full bg-title shrink-0"></span>
                <span><span class="important">Account Data</span>: Username and password (stored locally for authentication purposes).</span>
              </li>
              <li class="pl-4 flex items-center gap-2.5 mt-0.5">
                <span class="size-1.5 rounded-full bg-title shrink-0"></span>
                <span><span class="important">User Content</span>: Profile pictures uploaded by the user.</span>
              </li>
            </ul>
          </p>
        </li>
        <li class="caseli">
          <h3>2. How We Use Your Information</h3>
          <p>
            Your data is used strictly to run the basic features of the local website (e.g., displaying your profile and allowing login). <span class="important">We do not sell, rent, monetize, or share your data with any third parties.</span>
          </p>
        </li>
        <li class="caseli">
          <h3>3. Data Storage and Security</h3>
          <p>
            All data is stored locally within a database <span class="important">postgresql</span>.<br>
            Connection security is simulated using a <span class="important">local SSL certificate (HTTPS)</span>.<br>
            <span class="important">Important: Because this is a project, do not reuse passwords that you use for real-world personal accounts (like your personal email or banking)</span>.
          </p>
        </li>
        <li class="caseli">
          <h3>4. Third-Party Links and Tools</h3>
          <p>
            The site may contain assets or code snippets found on the internet or generated by AI, but <span class="important">it does not integrate third-party trackers, commercial analytics, or advertisement networks</span>.
          </p>
        </li>
        <li class="caseli">
          <h3>5. Changes to This Policy & Contact</h3>
          <p>
            As this is a closed school project with no dedicated support email or communication channel, this policy is static and may not be actively updated. Data is deleted when the local database is cleared or reset by the developers.
          </p>
        </li>
      </ul>

    </div>
  </BasePage>
</template>

<script setup>
</script>

<style scoped>
@import "@/style.css";

.caseli {
  @apply my-6
}
h3 {
  @apply text-title text-2xl font-semibold mb-3
}
br {
  @apply mb-4
}
p {
  @apply pl-4
}

.important {
  @apply font-black italic
}
</style>
