"""
Django settings for transcendence project.

Generated by 'django-admin startproject' using Django 5.2.13.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env()

# Take environment variables from .env file
env_file_path = os.path.join(BASE_DIR.parent, ".env")
environ.Env.read_env(env_file_path)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = "django-insecure-9qnoi)x8u$_th9@*cdp8vp23!i2kgwglwrc*q^n4d=sct6rdu2"
SECRET_KEY = env("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env("DEBUG").lower().startswith("t")

CSRF_COOKIE_SECURE = True
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True
SECURE_HSTS_SECONDS = 3600
SECURE_SSL_REDIRECT = False  # Handled by nginx reverse proxy
SESSION_COOKIE_SECURE = True
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

SILENCED_SYSTEM_CHECKS = [
    "security.W008"  # SECURE_SSL_REDIRECT
]

USE_X_FORWARDED_HOST = True
USE_X_FORWARDED_PORT = True
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
ALLOWED_HOSTS = ["*"]
CSRF_TRUSTED_ORIGINS = ["https://ft.lien.cat", "https://tla-ft.lien.cat"]

# Application definition

INSTALLED_APPS = [
    "daphne",
    "chat",
    "skribble",
    "tplace",
    "back.apps.BackConfig",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "django_extensions",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "back.middleware.UpdateLastSeenMiddleware",
]

ROOT_URLCONF = "transcendence.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "transcendence.wsgi.application"
ASGI_APPLICATION = "transcendence.asgi.application"

# Channels
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [("redis", 6379)],
        },
    },
}

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": env.db(),
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Europe/Paris"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = os.path.join(BASE_DIR, "static")
MEDIA_ROOT = "/media"
MEDIA_URL = "media/"

LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Redis connection URL - format: redis://[:password]@host:port/db
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis:6379/1",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        },
    }
}

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "INFO",
    },
}

# Chat history is stored separately from Channels and Django cache keys.
CHAT_REDIS_URL = env("CHAT_REDIS_URL", default="redis://redis:6379/2")
CHAT_HISTORY_LIMIT = env.int("CHAT_HISTORY_LIMIT", default=50)
CHAT_HISTORY_TTL = env.int("CHAT_HISTORY_TTL", default=60 * 60 * 2)
CHAT_MESSAGE_MAX_LENGTH = env.int("CHAT_MESSAGE_MAX_LENGTH", default=1000)

SKRIBBLE_REDIS_URL = env("SKRIBBLE_REDIS_URL", default="redis://redis:6379/3")
SKRIBBLE_HISTORY_LIMIT = env.int("SKRIBBLE_HISTORY_LIMIT", default=0)
SKRIBBLE_HISTORY_TTL = env.int("SKRIBBLE_HISTORY_TTL", default=120)

TPLACE_REDIS_URL = env("TPLACE_REDIS_URL", default="redis://redis:6379/4")
TPLACE_HISTORY_LIMIT = env.int("TPLACE_HISTORY_LIMIT", default=50)
TPLACE_HISTORY_TTL = env.int("TPLACE_HISTORY_TTL", default=120)

TPLACE_MAX_X = 2000
TPLACE_MAX_Y = 2000
