
map $http_upgrade $connection_upgrade {
  default upgrade;
  '' close;
}

# upstream server serve as aliases
upstream daphne {
  server back:8000;
}

server {
  listen 443 ssl;
  server_name localhost;

  http2 on;
  ssl_certificate /etc/nginx/ssl/cat.crt;
  ssl_certificate_key /etc/nginx/ssl/cat.key;
  ssl_protocols TLSv1.3;

  gzip on;
  gzip_vary on;
  gzip_proxied any;
  gzip_comp_level 6;
  gzip_types text/plain text/css text/xml application/json application/javascript application/xml+rss application/atom+xml image/svg+xml;

  root /usr/share/nginx/html;

  client_max_body_size 10M;

  location / {
    index index.html index.html;
    try_files $uri $uri.html $uri/ =404;
  }

  location /profile {
    try_files /profile.html =404;
  }

  location /profile/update {
    try_files /profile-update.html =404;
  }

  location ~ ^/login([^/]+)$ {
    try_files /login.html =404;
  }

  location ~ ^/signup([^/]+)$ {
    try_files /signup.html =404;
  }

  location ~ ^/chat([^/]+)$ {
    try_files /chat.html =404;
  }

  # Reverse proxi creation
  location /api {
    proxy_pass http://daphne; # Redirects API calls to backend container to avoid full links api calls
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection $connection_upgrade;

    proxy_set_header Host $host:${EXTERNAL_PORT};
    proxy_set_header X-Real-IP $remote_addr; # Gets client's real IP
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; # Gets all routes clients has taken to connect to host
    proxy_set_header X-Forwarded-Proto $scheme; # Tell Django request came through HTTPS
    proxy_set_header X-Forwarded-Port ${EXTERNAL_PORT};
  }

  location /media {
    proxy_pass http://daphne;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection $connection_upgrade;

    proxy_set_header Host $host:${EXTERNAL_PORT};
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-Port ${EXTERNAL_PORT};
  }

  location /static {
    proxy_pass http://daphne;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection $connection_upgrade;

    proxy_set_header Host $host:${EXTERNAL_PORT};
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-Port ${EXTERNAL_PORT};
  }

  # django admin
  location /admin {
    proxy_pass http://daphne;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection $connection_upgrade;

    proxy_set_header Host $host:${EXTERNAL_PORT};
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-Port ${EXTERNAL_PORT};
  }

  # Prevents the browser to do agressive caching by storing
  # cache up to one 1y
  location /assets/ {
    root /usr/share/nginx/html;
    expires 1y;
    add_header Cache-Control "public, immutable";
  }

  location /ws/ {
    proxy_pass http://daphne;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection $connection_upgrade;

    proxy_set_header Host $host:${EXTERNAL_PORT};
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-Port ${EXTERNAL_PORT};
  }

  # Redirects HTTP requests to https
  error_page 497 =301 https://$host:${EXTERNAL_PORT}$request_uri;

  # Redirects error 404 to 404.html
  error_page 404 /error_404.html;
  location = /error_404.html {
    root /usr/share/nginx/html;
    internal;
  }
}
