# Generated by Django 5.2.13 on 2026-05-12 15:08

import datetime

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("back", "0003_alter_userprofile_profile_image"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Color",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("color", models.TextField()),
                (
                    "cost",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WordList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name="userprofile",
            name="max_placable_pixels",
            field=models.IntegerField(
                default=10, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="next_regeneration",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="nyancoins",
            field=models.IntegerField(
                default=20, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="placable_pixels",
            field=models.IntegerField(
                default=10, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="regeneration_delay",
            field=models.DurationField(default=datetime.timedelta(seconds=60)),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="profile_image",
            field=models.ImageField(
                blank=True, max_length=255, null=True, upload_to="profile_images/"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="unlocked_colors",
            field=models.ManyToManyField(to="back.color"),
        ),
        migrations.CreateModel(
            name="Pixel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "x_pos",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                (
                    "y_pos",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "color",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="back.color"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Word",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("word", models.TextField(max_length=255)),
                (
                    "list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, to="back.wordlist"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="userprofile",
            name="unlocked_wordlists",
            field=models.ManyToManyField(to="back.wordlist"),
        ),
        migrations.AddConstraint(
            model_name="userprofile",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("placable_pixels__lte", models.F("max_placable_pixels"))
                ),
                name="placable_lte_max_placable_pixels",
            ),
        ),
    ]
