# Generated by Django 5.2.13 on 2026-06-09 12:50

from django.db import migrations, models

free_colors = {
    "#000000": "Black",
    "#FF1A1A": "Red",
    "#FF9900": "Orange",
    "#FFFF00": "Yellow",
    "#CCFF00": "Lime",
    "#33FF00": "Green",
    "#5A5A5A": "Dark Gray",
    "#990000": "Dark Red",
    "#804000": "Brown",
    "#667700": "Olive",
    "#1A7F00": "Dark Green",
    "#007F33": "Forest",
    "#A0A0A0": "Gray",
    "#1AD4D4": "Cyan",
    "#1A66FF": "Blue",
    "#4B00FF": "Indigo",
    "#CC00FF": "Magenta",
    "#FF0080": "Pink",
    "#FFFFFF": "White",
    "#0F7F7A": "Teal",
    "#0D3B7F": "Navy",
    "#2A0A7F": "Deep Blue",
    "#7A0A7F": "Purple",
    "#99004D": "Dark Pink",
}

paid_colors = {
    "#111111": "Almost Black",
    "#FF6B6B": "Coral",
    "#FFD166": "Amber",
    "#E9FF70": "Acid Yellow",
    "#70E000": "Fresh Green",
    "#38F2A4": "Aqua Mint",
    "#3D3D3D": "Charcoal",
    "#C1121F": "Ruby",
    "#BC6C25": "Caramel",
    "#7CB518": "Moss",
    "#2D6A4F": "Pine",
    "#00916E": "Emerald",
    "#BDBDBD": "Silver",
    "#00B4D8": "Sky Cyan",
    "#4895EF": "Azure",
    "#560BAD": "Violet",
    "#B5179E": "Fuchsia",
    "#F72585": "Hot Pink",
    "#F5F5F5": "Snow",
    "#2A9D8F": "Lagoon",
    "#1D3557": "Midnight",
    "#240046": "Deep Violet",
    "#5A189A": "Royal Purple",
    "#800F2F": "Wine",
}
default_color_cost = 100


def add_colors(apps, _schema_editor):
    Color = apps.get_model("back", "Color")
    for hex_code, name in free_colors.items():
        color = Color(hex_code=hex_code, name=name, cost=0)
        color.save()
    for hex_code, name in paid_colors.items():
        color = Color(hex_code=hex_code, name=name, cost=default_color_cost)
        color.save()


class Migration(migrations.Migration):
    dependencies = [
        ("back", "0004_color_wordlist_userprofile_max_placable_pixels_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="color",
            old_name="color",
            new_name="hex_code",
        ),
        migrations.AddField(
            model_name="color",
            name="name",
            field=models.TextField(default="???"),
            preserve_default=False,
        ),
        migrations.RunPython(add_colors),
    ]
