# Generated by Django 5.2.13 on 2026-06-09 13:10

from django.db import migrations


def create_userprofile_for_existing_users(apps, _schema_editor):
    UserProfile = apps.get_model("back", "UserProfile")
    User = apps.get_model("auth", "User")
    for user in User.objects.all():
        profile, _created = UserProfile.objects.get_or_create(user=user)
        profile.save()


def unlock_free_colors_for_existing_users(apps, _schema_editor):
    Color = apps.get_model("back", "Color")
    UserProfile = apps.get_model("back", "UserProfile")
    free_colors = Color.objects.filter(cost=0)
    for profile in UserProfile.objects.all():
        profile.unlocked_colors.set(
            set(list(profile.unlocked_colors.all()) + list(free_colors))
        )
        profile.save()


class Migration(migrations.Migration):
    dependencies = [
        ("back", "0005_auto_20260609_1450"),
    ]

    operations = [
        migrations.RunPython(create_userprofile_for_existing_users),
        migrations.RunPython(unlock_free_colors_for_existing_users),
    ]
