# Generated by Django 5.2.13 on 2026-06-23 12:25

import back.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("back", "0006_auto_20260609_1510"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="friends",
            field=models.ManyToManyField(to="back.userprofile"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="pending_friend_requests",
            field=models.ManyToManyField(to="back.userprofile"),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="profile_image",
            field=models.ImageField(
                blank=True,
                max_length=255,
                null=True,
                upload_to=back.models.get_image_path,
            ),
        ),
    ]
