# Generated by Django 5.2.13 on 2026-06-24 11:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("back", "0007_userprofile_friends_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="pixel",
            constraint=models.UniqueConstraint(
                fields=("x_pos", "y_pos"), name="pixel_uniq_pos"
            ),
        ),
    ]
