# Generated by Django 5.2.13 on 2026-06-24 12:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("back", "0008_pixel_pixel_uniq_pos"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="next_regeneration",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
