# Generated by Django 5.2.13 on 2026-06-24 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("back", "0009_alter_userprofile_next_regeneration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="word",
            name="list",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="words",
                to="back.wordlist",
            ),
        ),
    ]
