from django.db import migrations

basic_list = {
    "donkey",
    "stork",
    "snail",
    "narwhal",
    "goose",
    "panda",
    "horse",
    "hippopotamus",
    "eel",
    "fox",
    "cheetah",
    "crow",
    "rhinoceros",
    "poodle",
    "flamingo",
    "bat",
    "rat",
    "lobster",
    "frog",
    "sheep",
    "elephant",
    "deer",
    "penguin",
    "hummingbird",
    "cobra",
    "manatee",
    "stingray",
    "clam",
    "piranha",
    "blowfish",
    "skunk",
    "starfish",
    "cricket",
    "spider web",
    "bacteria",
    "beehive",
    "black widow",
    "cocoon",
    "paw",
    "claw",
    "fin",
    "pet",
    "howl",
    "angel",
    "giant",
    "monster",
    "unicorn",
    "dragon",
    "wooly mammoth",
    "sidekick",
    "rice",
    "onion",
    "pear",
    "mushroom",
    "soup",
    "pumpkin",
    "corn dog",
    "coconut",
    "bell pepper",
    "strawberry",
    "chocolate chip cookie",
    "vegetable",
    "drink",
    "radish",
    "french fries",
    "cracker",
    "loaf",
    "banana peel",
    "hot dog",
    "marshmallow",
    "corn",
    "gum",
    "oil",
    "tooth",
    "chin",
    "face",
    "lip",
    "knee",
    "mouth",
    "backbone",
    "muscle",
    "cheek",
    "dimple",
    "elbow",
    "wrist",
    "brain",
    "hip",
    "toe",
    "forehead",
    "doctor",
    "sunburn",
    "marry",
    "grandma",
    "baker",
    "queen",
    "butcher",
    "prince",
    "king",
    "teacher",
    "neighbor",
    "children",
    "cheerleader",
    "pirate",
    "newlywed",
    "hug",
    "kiss",
    "class",
    "toaster",
    "shower",
    "elevator",
    "chimney",
    "shelf",
    "bathtub",
    "mug",
    "bucket",
    "pan",
    "door",
    "doormat",
    "stove",
    "table",
    "cover",
    "rug",
    "faucet",
    "telephone",
    "whisk",
    "spoon",
    "mattress",
    "vase",
    "lid",
    "attic",
    "washing machine",
    "ironing board",
    "blanket",
    "front porch",
    "grill",
    "shampoo",
    "thermometer",
    "shade",
    "scarf",
    "bag",
    "watch",
    "stocking",
    "ring",
    "mitten",
    "jewelry",
    "bib",
    "cape",
    "sandal",
    "top hat",
    "belt",
    "pajamas",
    "t-shirt",
    "necktie",
    "coat",
    "blue jeans",
    "crown",
    "wallet",
    "sock",
    "baggage",
    "vest",
    "sunglasses",
    "lifejacket",
    "jacket",
    "suitcase",
    "present",
    "nail",
    "stick",
    "paint",
    "wheelbarrow",
    "cork",
    "hammer",
    "iron",
    "rake",
    "pitchfork",
    "chalk",
    "windshield",
    "frame",
    "battery",
    "screwdriver",
    "rope",
    "pipe",
    "bug spray",
    "paper",
    "glue",
    "colored pencil",
    "easel",
    "yardstick",
    "pail",
    "hook",
    "match",
    "wax",
    "key",
    "pencil",
    "notebook",
    "notepad",
    "magazine",
    "horn",
    "mud",
    "storm",
    "cactus",
    "rain",
    "crater",
    "root",
    "cliff",
    "snow",
    "ocean",
    "pond",
    "jungle",
    "beach",
    "rock",
    "snowflake",
    "plant",
    "cave",
    "forest",
    "dirt",
    "summer",
    "volcano",
    "ice",
    "flood",
    "pine tree",
    "twig",
    "seed",
    "wood",
    "slope",
    "wreath",
    "rocket",
    "trip",
    "truck",
    "bicycle",
    "bike",
    "dump truck",
    "subway",
    "yacht",
    "railroad",
    "oar",
    "lighthouse",
    "highway",
    "buggy",
    "minivan",
    "helicopter",
    "kayak",
    "limousine",
    "parachute",
    "submarine",
    "airport",
    "map",
    "compass",
    "globe",
    "hotel",
    "address",
    "America",
    "east",
    "garbage truck",
    "escalator",
    "wreck",
    "sleeping bag",
    "tent",
    "church",
    "garden",
    "sidewalk",
    "store",
    "cabin",
    "castle",
    "doghouse",
    "fire hydrant",
    "shopping cart",
    "tank",
    "tower",
    "roof",
    "state",
    "flagpole",
    "snowboarding",
    "flute",
    "golf",
    "hopscotch",
    "tennis",
    "skateboard",
    "ski",
    "kite",
    "pinwheel",
    "parachuting",
    "yo-yo",
    "trapeze",
    "cello",
    "puzzle",
    "trophy",
    "target",
    "dominoes",
    "chess",
    "camera",
    "hula hoop",
    "swim",
    "movie theater",
    "museum",
    "piano",
    "fishing pole",
    "lightsaber",
    "puppet",
    "free",
    "electricity",
    "cook",
    "lucky",
    "empty",
    "crack",
    "hole",
    "draw",
    "wedge",
    "shape",
    "save",
    "leak",
    "deep",
    "connect",
    "half",
    "pop",
    "chart",
    "list",
    "go",
    "eclipse",
    "third plate",
    "base",
    "spill",
    "day",
    "rattle",
    "curve",
    "see",
    "scale",
    "letter",
    "coin",
    "gold",
    "outer space",
    "solar system",
}
listname1 = "basic"


def add_word(apps, _schema_editor):
    WordList = apps.get_model("back", "WordList")
    wl = WordList(name=listname1)
    wl.save()
    Word = apps.get_model("back", "Word")
    for word in basic_list:
        word = Word(word=word, list=wl)
        word.save()


class Migration(migrations.Migration):
    dependencies = [
        ("back", "0010_alter_word_list"),
    ]

    operations = [
        migrations.RunPython(add_word),
    ]
