# Generated by Django 5.2.13 on 2026-06-25 11:46

import datetime

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("back", "0011_word_library"),
    ]

    operations = [
        migrations.CreateModel(
            name="SkribbleRoom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.TextField(max_length=5)),
                ("name", models.TextField(max_length=255, unique=True)),
                ("current_player_index", models.IntegerField(default=0)),
                ("round_counter", models.IntegerField(default=0)),
                ("round_started", models.BooleanField(default=False)),
                ("timer", models.DurationField(default=datetime.timedelta(seconds=60))),
                ("timer_end", models.DurationField(default=django.utils.timezone.now)),
                ("created_at", models.DurationField(default=django.utils.timezone.now)),
                (
                    "current_word",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="rooms_with_current_word",
                        to="back.word",
                    ),
                ),
                (
                    "wordlist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, to="back.wordlist"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SkribbleRoomWord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="back.skribbleroom",
                    ),
                ),
                (
                    "word",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="back.word"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="skribbleroom",
            name="word_history",
            field=models.ManyToManyField(
                related_name="rooms_with_word_in_history",
                through="back.SkribbleRoomWord",
                to="back.word",
            ),
        ),
        migrations.CreateModel(
            name="SkribblePlayer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                (
                    "score",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                ("found", models.BooleanField(default=False)),
                (
                    "player",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="back.userprofile",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="back.skribbleroom",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("room", "order"),
                        name="skribble_player_unique_order_per_room",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="skribbleroomword",
            constraint=models.UniqueConstraint(
                fields=("room", "word"), name="unique_room_word_history"
            ),
        ),
    ]
