# Generated by Django 5.2.13 on 2026-06-25 14:24

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    replaces = [
        ("back", "0013_alter_skribbleplayer_room"),
        ("back", "0014_remove_skribbleroom_created_at_and_more"),
        ("back", "0015_skribbleroom_created_at_skribbleroom_timer_end"),
        ("back", "0016_alter_skribbleroom_created_at"),
        ("back", "0017_alter_skribbleroom_current_word"),
        ("back", "0018_alter_skribbleroom_current_word"),
        ("back", "0019_alter_skribbleroom_code"),
        ("back", "0020_alter_skribbleplayer_order"),
        ("back", "0021_alter_skribbleplayer_order_and_more"),
    ]

    dependencies = [
        ("back", "0012_skribbleroom_skribbleroomword_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="skribbleplayer",
            name="room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="players",
                to="back.skribbleroom",
            ),
        ),
        migrations.RemoveField(
            model_name="skribbleroom",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="skribbleroom",
            name="timer_end",
        ),
        migrations.AddField(
            model_name="skribbleroom",
            name="timer_end",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="skribbleroom",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="skribbleroom",
            name="current_word",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="rooms_with_current_word",
                to="back.word",
            ),
        ),
        migrations.AlterField(
            model_name="skribbleroom",
            name="code",
            field=models.TextField(max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name="skribbleplayer",
            name="order",
            field=models.IntegerField(
                validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AlterField(
            model_name="skribbleplayer",
            name="score",
            field=models.IntegerField(
                default=0, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
    ]
