# Generated by Django 5.2.13 on 2026-06-27 16:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("back", "0013_alter_skribbleplayer_room_alter_skribbleplayer_order_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="skribbleroom",
            old_name="round_started",
            new_name="game_started",
        ),
    ]
