# Generated by Django 5.2.13 on 2026-06-27 16:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("back", "0014_rename_round_started_skribbleroom_game_started"),
    ]

    operations = [
        migrations.AddField(
            model_name="skribbleroom",
            name="turn_started",
            field=models.BooleanField(default=False),
        ),
    ]
