# Generated by Django 5.2.13 on 2026-07-02 15:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("back", "0017_skribble_game_flow"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="friends",
            field=models.ManyToManyField(blank=True, to="back.userprofile"),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="pending_friend_requests",
            field=models.ManyToManyField(blank=True, to="back.userprofile"),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="unlocked_wordlists",
            field=models.ManyToManyField(blank=True, to="back.wordlist"),
        ),
    ]
